// Turns the manifest into a whole voidbase app under `.voidbase/`: PocketBase's minimal layout (main.ts,
// package.json, pb_hooks/, pb_migrations/, pb_public/, pb_data/) plus the generated glue that imports the Void
// app's own modules. The project root stays a plain Void app and `.voidbase/` is git-ignored build output.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { VoidCron, VoidManifest } from "./scan";
import type { SecretsDeclaration } from "../node/secrets";

const BANNER = "// Generated by voidbase's Void adapter. Do not edit: `vite build` (or `voidbase adapt`) rewrites it.";
/** the import specifier the generated code uses for the adapter runtime; overridable so this repo can test itself */
export const ADAPTER_PACKAGE = "@voidbase-cloud/voidbase";

/** from inside .voidbase/, the app's own files are one directory up */
const importPath = (file: string) => "../" + file.replace(/\.(m?[tj]sx?)$/, "");
const ident = (prefix: string, i: number) => `${prefix}${i}`;

export interface GenerateOptions {
  /** package name the generated files import voidbase from */
  pkg?: string;
}

/** The bundle entry: imports the app's own modules and hands them to the hook runtime. Bundled into pb_hooks. */
export function generateServerModule(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  const lines: string[] = [BANNER, "//", "// The project's routes, middleware, vb_hooks, crons and queues, as one module for the generated pb_hooks bundle.", ""];
  lines.push(`import { mountVoidApp } from "${pkg}/adapter";`);
  m.routes.forEach((r, i) => lines.push(`import * as ${ident("route", i)} from "${importPath(r.file)}";`));
  m.middleware.forEach((x, i) => lines.push(`import ${ident("middleware", i)} from "${importPath(x.file)}";`));
  m.hooks.forEach((x, i) => lines.push(`import ${ident("hook", i)} from "${importPath(x.file)}";`));
  m.crons.forEach((x, i) => lines.push(`import * as ${ident("cron", i)} from "${importPath(x.file)}";`));
  m.queues.forEach((x, i) => lines.push(`import ${ident("queue", i)} from "${importPath(x.file)}";`));
  lines.push("", "export function register(): void {", "  mountVoidApp({");

  lines.push("    routes: [");
  m.routes.forEach((r, i) => {
    const splat = r.splat ? `, splat: ${JSON.stringify(r.splat)}` : "";
    lines.push(`      { url: ${JSON.stringify(r.url)}, hookPath: ${JSON.stringify(r.hookPath)}, methods: ${JSON.stringify(r.methods)}, params: ${JSON.stringify(r.params)}${splat}, mod: ${ident("route", i)} },`);
  });
  lines.push("    ],");

  lines.push("    hooks: [");
  m.hooks.forEach((x, i) => lines.push(`      { hook: ${JSON.stringify(x.hook)}, handler: ${ident("hook", i)} },`));
  lines.push("    ],");

  lines.push(`    middleware: [${m.middleware.map((_, i) => ident("middleware", i)).join(", ")}],`);

  lines.push("    crons: [");
  m.crons.forEach((c, i) => lines.push(`      { name: ${JSON.stringify(c.name)}, expr: ${ident("cron", i)}.cron, handler: ${ident("cron", i)}.default },`));
  lines.push("    ],");

  lines.push("    queues: [");
  m.queues.forEach((q, i) => lines.push(`      { name: ${JSON.stringify(q.name)}, binding: ${JSON.stringify(q.binding)}, consumer: ${ident("queue", i)} },`));
  lines.push("    ],");

  lines.push("  });", "}", "");
  return lines.join("\n");
}

/** The pb_hooks file that registers the bundle: the one place the hook globals are in scope. */
export function generateHookWrapper(crons: VoidCron[] = []): string {
  // one literal cronAdd(...) per cron, as a comment: the deploy reads the Worker's cron triggers out of the hook
  // files (hooks-plugin's cronTriggers), while the bundle registers the jobs with values it only has at runtime
  const triggers = crons.map((c) => `// cronAdd(${JSON.stringify(c.name)}, ${JSON.stringify(c.expr)})  crons/${c.name}: its schedule, read at build time for the Worker's cron triggers`).join("\n");
  return `${BANNER}
// The project's routes, middleware, vb_hooks, crons and queues. The code is in void-app.js beside this file, bundled
// because a hook cannot import from npm; this is where the hook globals it needs are in scope.
//
// \`__g\` is the object every hook file is handed its globals from: $app, $apis, routerAdd, routerUse, cronAdd, the
// error classes and every on* event registrar. Publishing it is what makes \`pb\` work inside the bundle, and it is
// published *before* the bundle is required so a module can register an event hook while it is initialising.
globalThis.__voidbaseHooks = __g;
${triggers ? `${triggers}\n` : ""}
require(\`\${__hooks}/void-app.js\`).register();
`;
}

/** The generated app's entry: the app's own voidbase extensions, and a Bun runner. */
export function generateMainEntry(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  const lines = [
    BANNER,
    "//",
    "// The voidbase app this Void project builds into: `bun .voidbase/main.ts` runs it, `voidbase deploy` from this",
    "// directory ships it. Edit the project, not this file.",
    "//",
    "// The whole app -- routes/, middleware/, crons/ and queues/ -- is compiled into pb_hooks, so nothing but the",
    "// runner is left here.",
    `import type { VoidbaseApp } from "${pkg}";`,
  ];
  lines.push("", "export function register(_app: VoidbaseApp) {");
  lines.push("  // nothing to register here: routes/, middleware/, crons/ and queues/ are the app's server code, and");
  lines.push("  // they are compiled into pb_hooks. Everything under src/ reaches PocketBase through them.");
  lines.push("}", "");
  lines.push(`if (import.meta.main) {
  // the Bun runtime, imported dynamically (and hidden from the bundler) because \`voidbase deploy\` composes this
  // file into the Worker for register() only, and the runtime entry pulls in bun:sqlite and the filesystem shims
  const runtime = "${pkg}";
  const { voidbase, parseServeArgs } = (await import(/* @vite-ignore */ runtime)) as typeof import("${pkg}");
  // this app's directories sit next to this file, so it runs the same from any working directory
  const flags = parseServeArgs(process.argv.slice(2).filter((a) => a !== "serve"));
  for (const key of Object.keys(flags) as (keyof typeof flags)[]) if (flags[key] === undefined) delete flags[key];
  const app = await voidbase({
    dir: \`\${import.meta.dir}/pb_data\`,
    hooksDir: process.env.VOIDBASE_HOOKS_DIR ?? \`\${import.meta.dir}/pb_hooks\`,
    migrationsDir: process.env.VOIDBASE_MIGRATIONS_DIR ?? \`\${import.meta.dir}/pb_migrations\`,
    pluginsDir: process.env.VOIDBASE_PLUGINS_DIR ?? \`\${import.meta.dir}/pb_plugins\`,
    publicDir: \`\${import.meta.dir}/pb_public\`,
    ...flags,
  });
  register(app);
  await app.start();
}
`);
  return lines.join("\n");
}

/** The generated app's package.json: enough for voidbase deploy to read the dependency spec and for Bun to run it. */
export function generatePackageJson(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  let spec = "latest";
  try {
    const parent = JSON.parse(readFileSync(join(m.root, "package.json"), "utf8")) as { name?: string; dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
    spec = parent.dependencies?.[pkg] ?? parent.devDependencies?.[pkg] ?? spec;
    return JSON.stringify({ name: `${parent.name ?? "app"}-voidbase`, private: true, type: "module", main: "main.ts", dependencies: { [pkg]: spec } }, null, 2) + "\n";
  } catch {
    return JSON.stringify({ name: "app-voidbase", private: true, type: "module", main: "main.ts", dependencies: { [pkg]: spec } }, null, 2) + "\n";
  }
}

/** Drizzle separates statements with its own marker; without it fall back to semicolons at end of line. */
export function splitSql(sql: string): string[] {
  const source = sql.includes("--> statement-breakpoint") ? sql.split("--> statement-breakpoint") : sql.split(/;\s*$/m);
  return source.map((s) => s.replace(/^\s*--.*$/gm, "").trim().replace(/;$/, "")).filter(Boolean);
}

/** A Drizzle .sql migration as a PocketBase-style migration, so both runtimes apply it through the same runner. */
export function generateMigration(name: string, sql: string): string {
  const statements = splitSql(sql);
  return `${BANNER}
// Generated from db/migrations/${name}.sql (Drizzle). voidbase records it in _pbMigrations like any other migration.
migrate(async (app) => {
${statements.map((s) => `  await app.execSQL(${JSON.stringify(s)});`).join("\n")}
}, async (_app) => {
  // Drizzle migrations carry no down step; roll back with a new migration.
});
`;
}

// Void's codegen maps void/db and void/queues to declaration files in .void/ (schema-aware types for tsc). Bun
// honours tsconfig paths at runtime too, so under voidbase those imports would resolve to a .d.ts and export
// nothing. These shims take the values from the published runtime and the types from Void's declarations, and the
// generated .voidbase/tsconfig.json points the two mappings at them, so both tsc and Bun get what they need.
const DB_REEXPORTS = "and, asc, avg, between, count, createDb, desc, eq, exists, gt, gte, ilike, inArray, isNotNull, isNull, like, lt, lte, max, min, ne, not, notBetween, notExists, notInArray, notLike, or, sql, sum";

export function generateDbShim(): string {
  // void/_db is the same runtime module under a specifier the path mapping does not cover, so the shim can import
  // it without importing itself; the schema-aware types still come from Void's own declaration.
  return `${BANNER}
// void/db for a voidbase app: Drizzle over voidbase's D1 binding, typed by .void/db.d.ts.
import type * as Typed from "../.void/db";
import { db as runtimeDb } from "void/_db";

export { ${DB_REEXPORTS} } from "void/_db";
export const db: typeof Typed.db = runtimeDb as never;
`;
}

export function generateQueuesShim(): string {
  // Void has no unmapped alias for the queue producers, so the shim is the same one-line proxy Void ships: a
  // binding lookup per queue name. The adapter puts those bindings on the env (src/adapter/runtime.ts).
  return `${BANNER}
// void/queues for a voidbase app: the producers the adapter overlays on the env, typed by .void/queues.d.ts.
import { requireRuntimeBinding } from "void/_env";
import type * as Typed from "../.void/queues";

export const queues: typeof Typed.queues = new Proxy({}, {
  get: (_target, name: string) => requireRuntimeBinding(\`QUEUE_\${name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}\`),
}) as never;
`;
}

/** Void's tsconfig fragment with the two runtime-breaking mappings repointed at the shims. */
export function generateTsconfig(root: string): string | null {
  const voidTs = join(root, ".void", "tsconfig.json");
  // A fresh checkout has no .void/ yet: Void writes it during its own build, after the project's tsconfig (which
  // extends the fragment written here) has already been read. Rather than run anything -- a build must never wait
  // on a child process it did not need, and this one hung about one build in ten -- the fragment is written from
  // what this adapter knows, and the pass at the end of the build replaces it once .void/ is there.
  if (!existsSync(voidTs)) return JSON.stringify({ compilerOptions: { paths: { "void/db": ["./shim-db.ts"], "void/queues": ["./shim-queues.ts"] } } }, null, 2) + "\n";
  const base = JSON.parse(readFileSync(voidTs, "utf8")) as { compilerOptions?: { paths?: Record<string, string[]> } };
  const paths: Record<string, string[]> = {};
  for (const [key, targets] of Object.entries(base.compilerOptions?.paths ?? {})) {
    // .void and .voidbase sit at the same depth, so a target of the base config is rewritten once
    paths[key] = targets.map((t) => (t.startsWith("./") ? `../.void/${t.slice(2)}` : t));
  }
  if (paths["void/db"]) paths["void/db"] = ["./shim-db.ts"];
  if (paths["void/queues"]) paths["void/queues"] = ["./shim-queues.ts"];
  return JSON.stringify({ extends: "../.void/tsconfig.json", compilerOptions: { paths } }, null, 2) + "\n";
}

export interface WriteResult { written: string[]; removed: string[] }

const OUT = ".voidbase";

/** whether anything under Void's server conventions has to run */
export const hasServerCode = (m: VoidManifest) => !!(m.routes.length || m.middleware.length || m.crons.length || m.queues.length);

/** Writes the whole generated app under `<root>/.voidbase`. Everything in there is build output. */
/** pb_secrets/main.ts: the project's declaration, re-exported where `voidbase serve` and `voidbase deploy` look for it. */
export function generateSecretsDeclaration(d: SecretsDeclaration): string {
  const target = "../" + importPath(d.file.replace(/\.(ts|js|mjs)$/, "")); // pb_secrets/ is one level below .voidbase/
  const lines = [BANNER, "//", `// The app's configuration is declared in ${d.file}: ${d.names.map((n) => `${n} (${d.access[n]})`).join(", ") || "nothing yet"}.`, "// voidbase serve and voidbase deploy import it from here; the local values are in secrets.json beside this file.", `export { default } from "${target}";`, ""];
  return lines.join("\n");
}

export function writeVoidbaseApp(m: VoidManifest, opts: GenerateOptions & { migrations?: boolean } = {}): WriteResult {
  const written: string[] = [];
  const removed: string[] = [];
  const put = (rel: string, body: string) => {
    const full = join(m.root, OUT, rel);
    mkdirSync(dirname(full), { recursive: true });
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) writeFileSync(full, body);
    written.push(`${OUT}/${rel}`);
  };
  const drop = (rel: string) => {
    const full = join(m.root, OUT, rel);
    if (!existsSync(full)) return;
    rmSync(full, { recursive: true, force: true });
    removed.push(`${OUT}/${rel}`);
  };

  // PocketBase's minimal layout, generated whole: https://pocketbase.io/docs/going-to-production/#minimal-setup
  put("main.ts", generateMainEntry(m, opts));
  put("package.json", generatePackageJson(m, opts));
  put(".gitignore", "# the generated voidbase app is build output; this is what it makes at runtime\npb_data/\n# the values of the secrets vb_secrets/main.ts declares (copied from vb_secrets/secrets.json)\npb_secrets/secrets.json\n# the Void project voidbase deploy writes when the package is installed under node_modules\n.cloud/\n");

  // the tsconfig fragment the project's own tsconfig extends, and the shims it points at
  const tsconfig = generateTsconfig(m.root);
  if (tsconfig) {
    put("tsconfig.json", tsconfig);
    if (/"void\/db"/.test(tsconfig)) put("shim-db.ts", generateDbShim());
    if (/"void\/queues"/.test(tsconfig)) put("shim-queues.ts", generateQueuesShim());
  }

  // routes/, middleware/, crons/ and queues/ become a pb_hooks bundle; this is the module the bundler builds
  drop("pb_hooks");
  if (hasServerCode(m)) put("void-entry.ts", generateServerModule(m, opts));
  else drop("void-entry.ts");

  // pb_migrations: the project's vb_migrations/, plus one per Drizzle migration
  const migrationsOut = join(m.root, OUT, "pb_migrations");
  drop("pb_migrations");
  if (m.extras.migrationsDir) {
    cpSync(join(m.root, m.extras.migrationsDir), migrationsOut, { recursive: true });
    written.push(`${OUT}/pb_migrations`);
    removed.pop();
  }
  if (opts.migrations !== false && m.migrations.length) {
    mkdirSync(migrationsOut, { recursive: true });
    for (const mig of m.migrations) {
      const sql = readFileSync(resolve(m.root, mig.file), "utf8");
      put(`pb_migrations/${mig.name}.void.js`, generateMigration(mig.name, sql));
    }
  }
  if (existsSync(migrationsOut) && !readdirSync(migrationsOut).length) rmSync(migrationsOut, { recursive: true, force: true });

  // pb_plugins and voidbase.lock: what `voidbase plugins add` installed at the project root, carried in as they are.
  // They are pinned by hash and verified when the app starts, so the generated app runs them and a deploy from
  // .voidbase/ finds them; a stale copy is replaced whole, and one the project no longer has is removed.
  const carry = (rel: string) => {
    const src = join(m.root, rel); const out = join(m.root, OUT, rel);
    if (!existsSync(src)) { drop(rel); return; }
    rmSync(out, { recursive: true, force: true });
    cpSync(src, out, { recursive: true });
    written.push(`${OUT}/${rel}`);
  };
  carry("voidbase.lock");
  carry("pb_plugins");

  // pb_secrets: the declaration vb_secrets/main.ts makes, where `voidbase serve` and `voidbase deploy` look for it
  // (a re-export: the validators and their types stay the project's), and the local values beside it
  drop("pb_secrets");
  if (m.secrets) {
    put("pb_secrets/main.ts", generateSecretsDeclaration(m.secrets));
    const values = join(m.root, m.extras.secretsDir!, "secrets.json");
    if (existsSync(values)) { cpSync(values, join(m.root, OUT, "pb_secrets/secrets.json")); written.push(`${OUT}/pb_secrets/secrets.json`); }
  }

  return { written, removed };
}
