// Turns the manifest into the files a voidbase app is made of: `.voidbase/void-app.ts` (the generated glue that
// imports the app's own modules), `main.ts` (voidbase's composition entry, written once and then left alone) and
// one `pb_migrations/*.js` per Drizzle migration. Everything here is pure string building plus writes.
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { VoidManifest } from "./scan";

const BANNER = "// Generated by voidbase's Void adapter. Do not edit: `vite build` (or `voidbase adapt`) rewrites it.";
/** the import specifier the generated code uses for the adapter runtime; overridable so this repo can test itself */
export const ADAPTER_PACKAGE = "@voidbase-cloud/voidbase";

const importPath = (file: string) => "../" + file.replace(/\.(m?[tj]sx?)$/, "");
const ident = (prefix: string, i: number) => `${prefix}${i}`;

export interface GenerateOptions {
  /** package name the generated files import voidbase from */
  pkg?: string;
}

export function generateServerModule(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  const lines: string[] = [BANNER, "//", "// Void app -> voidbase: routes, middleware, crons and queues, mounted on the running app.", ""];
  lines.push(`import type { VoidbaseApp } from "${pkg}";`);
  lines.push(`import { mountVoidApp } from "${pkg}/adapter";`);
  m.routes.forEach((r, i) => lines.push(`import * as ${ident("route", i)} from "${importPath(r.file)}";`));
  m.middleware.forEach((x, i) => lines.push(`import ${ident("middleware", i)} from "${importPath(x.file)}";`));
  m.crons.forEach((x, i) => lines.push(`import * as ${ident("cron", i)} from "${importPath(x.file)}";`));
  m.queues.forEach((x, i) => lines.push(`import ${ident("queue", i)} from "${importPath(x.file)}";`));
  lines.push("", "export function register(app: VoidbaseApp): void {", "  mountVoidApp(app, {");

  lines.push("    routes: [");
  m.routes.forEach((r, i) => {
    const splat = r.splat ? `, splat: ${JSON.stringify(r.splat)}` : "";
    lines.push(`      { url: ${JSON.stringify(r.url)}, hookPath: ${JSON.stringify(r.hookPath)}, methods: ${JSON.stringify(r.methods)}, params: ${JSON.stringify(r.params)}${splat}, mod: ${ident("route", i)} },`);
  });
  lines.push("    ],");

  lines.push(`    middleware: [${m.middleware.map((_, i) => ident("middleware", i)).join(", ")}],`);

  lines.push("    crons: [");
  m.crons.forEach((c, i) => lines.push(`      { name: ${JSON.stringify(c.name)}, expr: ${ident("cron", i)}.cron, handler: ${ident("cron", i)}.default },`));
  lines.push("    ],");

  lines.push("    queues: [");
  m.queues.forEach((q, i) => lines.push(`      { name: ${JSON.stringify(q.name)}, binding: ${JSON.stringify(q.binding)}, consumer: ${ident("queue", i)} },`));
  lines.push("    ],");

  lines.push("  });", "}", "");
  return lines.join("\n");
}

/** voidbase's composition entry: `register(app)` for the deploy, and a Bun runner for `bun main.ts`. */
export function generateMainEntry(opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  return `// The voidbase entry for this Void app: \`bun main.ts\` locally, composed into the Worker by \`voidbase deploy\`.
// The generated glue in .voidbase/ carries routes, middleware, crons and queues; add your own extensions below it.
import type { VoidbaseApp } from "${pkg}";
import { register as registerVoidApp } from "./.voidbase/void-app";

export function register(app: VoidbaseApp) {
  registerVoidApp(app);
  // your own hooks and routes go here (app.hooks.routerAdd, app.hooks.onRecordCreate, ...)
}

if (import.meta.main) {
  const runtime = "${pkg}";
  const { voidbase, parseServeArgs } = (await import(/* @vite-ignore */ runtime)) as typeof import("${pkg}");
  const app = await voidbase(parseServeArgs(process.argv.slice(2).filter((a) => a !== "serve")));
  register(app);
  await app.start();
}
`;
}

/** Drizzle separates statements with its own marker; without it fall back to semicolons at end of line. */
export function splitSql(sql: string): string[] {
  const source = sql.includes("--> statement-breakpoint") ? sql.split("--> statement-breakpoint") : sql.split(/;\s*$/m);
  return source.map((s) => s.replace(/^\s*--.*$/gm, "").trim().replace(/;$/, "")).filter(Boolean);
}

/** A Drizzle .sql migration as a PocketBase-style migration, so both runtimes apply it through the same runner. */
export function generateMigration(name: string, sql: string): string {
  const statements = splitSql(sql);
  return `${BANNER}
// Generated from db/migrations/${name}.sql (Drizzle). voidbase records it in _pbMigrations like any other migration.
migrate(async (app) => {
${statements.map((s) => `  await app.execSQL(${JSON.stringify(s)});`).join("\n")}
}, async (_app) => {
  // Drizzle migrations carry no down step; roll back with a new migration.
});
`;
}

// Void's codegen maps void/db and void/queues to declaration files in .void/ (schema-aware types for tsc). Bun
// honours tsconfig paths at runtime too, so under voidbase those imports would resolve to a .d.ts and export
// nothing. These shims take the values from the published runtime and the types from Void's declarations, and the
// generated .voidbase/tsconfig.json points the two mappings at them, so both tsc and Bun get what they need.
const DB_REEXPORTS = "and, asc, avg, between, count, createDb, desc, eq, exists, gt, gte, ilike, inArray, isNotNull, isNull, like, lt, lte, max, min, ne, not, notBetween, notExists, notInArray, notLike, or, sql, sum";

export function generateDbShim(): string {
  // void/_db is the same runtime module under a specifier the path mapping does not cover, so the shim can import
  // it without importing itself; the schema-aware types still come from Void's own declaration.
  return `${BANNER}
// void/db for a voidbase app: Drizzle over voidbase's D1 binding, typed by .void/db.d.ts.
import type * as Typed from "../.void/db";
import { db as runtimeDb } from "void/_db";

export { ${DB_REEXPORTS} } from "void/_db";
export const db: typeof Typed.db = runtimeDb as never;
`;
}

export function generateQueuesShim(): string {
  // Void has no unmapped alias for the queue producers, so the shim is the same one-line proxy Void ships: a
  // binding lookup per queue name. The adapter puts those bindings on the env (src/adapter/runtime.ts).
  return `${BANNER}
// void/queues for a voidbase app: the producers the adapter overlays on the env, typed by .void/queues.d.ts.
import { requireRuntimeBinding } from "void/_env";
import type * as Typed from "../.void/queues";

export const queues: typeof Typed.queues = new Proxy({}, {
  get: (_target, name: string) => requireRuntimeBinding(\`QUEUE_\${name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}\`),
}) as never;
`;
}

/** Void's tsconfig fragment with the two runtime-breaking mappings repointed at the shims. */
export function generateTsconfig(root: string): string | null {
  const voidTs = join(root, ".void", "tsconfig.json");
  if (!existsSync(voidTs)) return null;
  const base = JSON.parse(readFileSync(voidTs, "utf8")) as { compilerOptions?: { paths?: Record<string, string[]> } };
  const paths: Record<string, string[]> = {};
  for (const [key, targets] of Object.entries(base.compilerOptions?.paths ?? {})) {
    // .void and .voidbase sit at the same depth, so a target of the base config is rewritten once
    paths[key] = targets.map((t) => (t.startsWith("./") ? `../.void/${t.slice(2)}` : t));
  }
  if (paths["void/db"]) paths["void/db"] = ["./shim-db.ts"];
  if (paths["void/queues"]) paths["void/queues"] = ["./shim-queues.ts"];
  return JSON.stringify({ extends: "../.void/tsconfig.json", compilerOptions: { paths } }, null, 2) + "\n";
}

export interface WriteResult { written: string[]; removed: string[] }

/** Writes the generated files under the app root. `main.ts` is only created when absent: it is the user's file. */
export function writeVoidbaseApp(m: VoidManifest, opts: GenerateOptions & { migrations?: boolean } = {}): WriteResult {
  const written: string[] = [];
  const removed: string[] = [];
  const put = (rel: string, body: string) => {
    const full = join(m.root, rel);
    mkdirSync(dirname(full), { recursive: true });
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) writeFileSync(full, body);
    written.push(rel);
  };

  const tsconfig = generateTsconfig(m.root);
  if (tsconfig) {
    put(".voidbase/tsconfig.json", tsconfig);
    if (/"void\/db"/.test(tsconfig)) put(".voidbase/shim-db.ts", generateDbShim());
    if (/"void\/queues"/.test(tsconfig)) put(".voidbase/shim-queues.ts", generateQueuesShim());
  }

  if (m.mode === "server") {
    put(".voidbase/void-app.ts", generateServerModule(m, opts));
    if (!existsSync(join(m.root, "main.ts"))) put("main.ts", generateMainEntry(opts));
  } else if (existsSync(join(m.root, ".voidbase/void-app.ts"))) {
    // the app lost its last route: leave no stale glue behind for main.ts to import
    rmSync(join(m.root, ".voidbase/void-app.ts"));
    removed.push(".voidbase/void-app.ts");
  }

  if (opts.migrations !== false) {
    for (const mig of m.migrations) {
      const sql = readFileSync(resolve(m.root, mig.file), "utf8");
      put(`pb_migrations/${mig.name}.void.js`, generateMigration(mig.name, sql));
    }
  }
  return { written, removed };
}
