// Turns the manifest into a whole voidbase app under `.voidbase/`: PocketBase's minimal layout (main.ts,
// package.json, pb_hooks/, pb_migrations/, pb_public/, pb_data/) plus the generated glue that imports the Void
// app's own modules. The project root stays a plain Void app and `.voidbase/` is git-ignored build output.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { VoidManifest } from "./scan";

const BANNER = "// Generated by voidbase's Void adapter. Do not edit: `vite build` (or `voidbase adapt`) rewrites it.";
/** the import specifier the generated code uses for the adapter runtime; overridable so this repo can test itself */
export const ADAPTER_PACKAGE = "@voidbase-cloud/voidbase";

/** from inside .voidbase/, the app's own files are one directory up */
const importPath = (file: string) => "../" + file.replace(/\.(m?[tj]sx?)$/, "");
const ident = (prefix: string, i: number) => `${prefix}${i}`;

export interface GenerateOptions {
  /** package name the generated files import voidbase from */
  pkg?: string;
}

export function generateServerModule(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  const lines: string[] = [BANNER, "//", "// Void app -> voidbase: routes, middleware, crons and queues, mounted on the running app.", ""];
  lines.push(`import type { VoidbaseApp } from "${pkg}";`);
  lines.push(`import { mountVoidApp } from "${pkg}/adapter";`);
  m.routes.forEach((r, i) => lines.push(`import * as ${ident("route", i)} from "${importPath(r.file)}";`));
  m.middleware.forEach((x, i) => lines.push(`import ${ident("middleware", i)} from "${importPath(x.file)}";`));
  m.crons.forEach((x, i) => lines.push(`import * as ${ident("cron", i)} from "${importPath(x.file)}";`));
  m.queues.forEach((x, i) => lines.push(`import ${ident("queue", i)} from "${importPath(x.file)}";`));
  lines.push("", "export function register(app: VoidbaseApp): void {", "  mountVoidApp(app, {");

  lines.push("    routes: [");
  m.routes.forEach((r, i) => {
    const splat = r.splat ? `, splat: ${JSON.stringify(r.splat)}` : "";
    lines.push(`      { url: ${JSON.stringify(r.url)}, hookPath: ${JSON.stringify(r.hookPath)}, methods: ${JSON.stringify(r.methods)}, params: ${JSON.stringify(r.params)}${splat}, mod: ${ident("route", i)} },`);
  });
  lines.push("    ],");

  lines.push(`    middleware: [${m.middleware.map((_, i) => ident("middleware", i)).join(", ")}],`);

  lines.push("    crons: [");
  m.crons.forEach((c, i) => lines.push(`      { name: ${JSON.stringify(c.name)}, expr: ${ident("cron", i)}.cron, handler: ${ident("cron", i)}.default },`));
  lines.push("    ],");

  lines.push("    queues: [");
  m.queues.forEach((q, i) => lines.push(`      { name: ${JSON.stringify(q.name)}, binding: ${JSON.stringify(q.binding)}, consumer: ${ident("queue", i)} },`));
  lines.push("    ],");

  lines.push("  });", "}", "");
  return lines.join("\n");
}

/** The generated app's entry: the Void glue, the app's own voidbase extensions, and a Bun runner. */
export function generateMainEntry(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  const hasGlue = m.mode === "server" && (m.routes.length || m.middleware.length || m.crons.length || m.queues.length);
  const lines = [
    BANNER,
    "//",
    "// The voidbase app this Void project builds into: `bun .voidbase/main.ts` runs it, `voidbase deploy` from this",
    "// directory ships it. Edit the project, not this file.",
    `import type { VoidbaseApp } from "${pkg}";`,
  ];
  if (hasGlue) lines.push('import { register as registerVoidApp } from "./void-app";');
  if (m.extras.register) lines.push(`import { register as registerApp } from "${importPath(m.extras.register)}";`);
  lines.push("", "export function register(app: VoidbaseApp) {");
  if (hasGlue) lines.push("  registerVoidApp(app); // routes/, middleware/, crons/, queues/");
  if (m.extras.register) lines.push(`  registerApp(app); // ${m.extras.register}`);
  if (!hasGlue && !m.extras.register) lines.push("  // nothing to register: the project has no server code of its own");
  lines.push("}", "");
  lines.push(`if (import.meta.main) {
  // the Bun runtime, imported dynamically (and hidden from the bundler) because \`voidbase deploy\` composes this
  // file into the Worker for register() only, and the runtime entry pulls in bun:sqlite and the filesystem shims
  const runtime = "${pkg}";
  const { voidbase, parseServeArgs } = (await import(/* @vite-ignore */ runtime)) as typeof import("${pkg}");
  const app = await voidbase(parseServeArgs(process.argv.slice(2).filter((a) => a !== "serve")));
  register(app);
  await app.start();
}
`);
  return lines.join("\n");
}

/** The generated app's package.json: enough for voidbase deploy to read the dependency spec and for Bun to run it. */
export function generatePackageJson(m: VoidManifest, opts: GenerateOptions = {}): string {
  const pkg = opts.pkg ?? ADAPTER_PACKAGE;
  let spec = "latest";
  try {
    const parent = JSON.parse(readFileSync(join(m.root, "package.json"), "utf8")) as { name?: string; dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
    spec = parent.dependencies?.[pkg] ?? parent.devDependencies?.[pkg] ?? spec;
    return JSON.stringify({ name: `${parent.name ?? "app"}-voidbase`, private: true, type: "module", main: "main.ts", dependencies: { [pkg]: spec } }, null, 2) + "\n";
  } catch {
    return JSON.stringify({ name: "app-voidbase", private: true, type: "module", main: "main.ts", dependencies: { [pkg]: spec } }, null, 2) + "\n";
  }
}

/** Drizzle separates statements with its own marker; without it fall back to semicolons at end of line. */
export function splitSql(sql: string): string[] {
  const source = sql.includes("--> statement-breakpoint") ? sql.split("--> statement-breakpoint") : sql.split(/;\s*$/m);
  return source.map((s) => s.replace(/^\s*--.*$/gm, "").trim().replace(/;$/, "")).filter(Boolean);
}

/** A Drizzle .sql migration as a PocketBase-style migration, so both runtimes apply it through the same runner. */
export function generateMigration(name: string, sql: string): string {
  const statements = splitSql(sql);
  return `${BANNER}
// Generated from db/migrations/${name}.sql (Drizzle). voidbase records it in _pbMigrations like any other migration.
migrate(async (app) => {
${statements.map((s) => `  await app.execSQL(${JSON.stringify(s)});`).join("\n")}
}, async (_app) => {
  // Drizzle migrations carry no down step; roll back with a new migration.
});
`;
}

// Void's codegen maps void/db and void/queues to declaration files in .void/ (schema-aware types for tsc). Bun
// honours tsconfig paths at runtime too, so under voidbase those imports would resolve to a .d.ts and export
// nothing. These shims take the values from the published runtime and the types from Void's declarations, and the
// generated .voidbase/tsconfig.json points the two mappings at them, so both tsc and Bun get what they need.
const DB_REEXPORTS = "and, asc, avg, between, count, createDb, desc, eq, exists, gt, gte, ilike, inArray, isNotNull, isNull, like, lt, lte, max, min, ne, not, notBetween, notExists, notInArray, notLike, or, sql, sum";

export function generateDbShim(): string {
  // void/_db is the same runtime module under a specifier the path mapping does not cover, so the shim can import
  // it without importing itself; the schema-aware types still come from Void's own declaration.
  return `${BANNER}
// void/db for a voidbase app: Drizzle over voidbase's D1 binding, typed by .void/db.d.ts.
import type * as Typed from "../.void/db";
import { db as runtimeDb } from "void/_db";

export { ${DB_REEXPORTS} } from "void/_db";
export const db: typeof Typed.db = runtimeDb as never;
`;
}

export function generateQueuesShim(): string {
  // Void has no unmapped alias for the queue producers, so the shim is the same one-line proxy Void ships: a
  // binding lookup per queue name. The adapter puts those bindings on the env (src/adapter/runtime.ts).
  return `${BANNER}
// void/queues for a voidbase app: the producers the adapter overlays on the env, typed by .void/queues.d.ts.
import { requireRuntimeBinding } from "void/_env";
import type * as Typed from "../.void/queues";

export const queues: typeof Typed.queues = new Proxy({}, {
  get: (_target, name: string) => requireRuntimeBinding(\`QUEUE_\${name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}\`),
}) as never;
`;
}

/** Void's tsconfig fragment with the two runtime-breaking mappings repointed at the shims. */
export function generateTsconfig(root: string): string | null {
  const voidTs = join(root, ".void", "tsconfig.json");
  if (!existsSync(voidTs)) return null;
  const base = JSON.parse(readFileSync(voidTs, "utf8")) as { compilerOptions?: { paths?: Record<string, string[]> } };
  const paths: Record<string, string[]> = {};
  for (const [key, targets] of Object.entries(base.compilerOptions?.paths ?? {})) {
    // .void and .voidbase sit at the same depth, so a target of the base config is rewritten once
    paths[key] = targets.map((t) => (t.startsWith("./") ? `../.void/${t.slice(2)}` : t));
  }
  if (paths["void/db"]) paths["void/db"] = ["./shim-db.ts"];
  if (paths["void/queues"]) paths["void/queues"] = ["./shim-queues.ts"];
  return JSON.stringify({ extends: "../.void/tsconfig.json", compilerOptions: { paths } }, null, 2) + "\n";
}

export interface WriteResult { written: string[]; removed: string[] }

const OUT = ".voidbase";

/** Writes the whole generated app under `<root>/.voidbase`. Everything in there is build output. */
export function writeVoidbaseApp(m: VoidManifest, opts: GenerateOptions & { migrations?: boolean } = {}): WriteResult {
  const written: string[] = [];
  const removed: string[] = [];
  const put = (rel: string, body: string) => {
    const full = join(m.root, OUT, rel);
    mkdirSync(dirname(full), { recursive: true });
    if (!existsSync(full) || readFileSync(full, "utf8") !== body) writeFileSync(full, body);
    written.push(`${OUT}/${rel}`);
  };
  const drop = (rel: string) => {
    const full = join(m.root, OUT, rel);
    if (!existsSync(full)) return;
    rmSync(full, { recursive: true, force: true });
    removed.push(`${OUT}/${rel}`);
  };

  // PocketBase's minimal layout, generated whole: https://pocketbase.io/docs/going-to-production/#minimal-setup
  put("main.ts", generateMainEntry(m, opts));
  put("package.json", generatePackageJson(m, opts));
  put(".gitignore", "# the generated voidbase app is build output; this is what it makes at runtime\npb_data/\n");

  // the tsconfig fragment the project's own tsconfig extends, and the shims it points at
  const tsconfig = generateTsconfig(m.root);
  if (tsconfig) {
    put("tsconfig.json", tsconfig);
    if (/"void\/db"/.test(tsconfig)) put("shim-db.ts", generateDbShim());
    if (/"void\/queues"/.test(tsconfig)) put("shim-queues.ts", generateQueuesShim());
  }

  if (m.routes.length || m.middleware.length || m.crons.length || m.queues.length) put("void-app.ts", generateServerModule(m, opts));
  else drop("void-app.ts"); // the project lost its last route: leave no stale glue for main.ts to import

  // pb_hooks: the project's own, copied in as they are
  drop("pb_hooks");
  if (m.extras.hooksDir) {
    cpSync(join(m.root, m.extras.hooksDir), join(m.root, OUT, "pb_hooks"), { recursive: true });
    written.push(`${OUT}/pb_hooks`);
    removed.pop(); // it was replaced, not dropped
  }

  // pb_migrations: the project's own, plus one per Drizzle migration
  const migrationsOut = join(m.root, OUT, "pb_migrations");
  drop("pb_migrations");
  if (m.extras.migrationsDir) {
    cpSync(join(m.root, m.extras.migrationsDir), migrationsOut, { recursive: true });
    written.push(`${OUT}/pb_migrations`);
    removed.pop();
  }
  if (opts.migrations !== false && m.migrations.length) {
    mkdirSync(migrationsOut, { recursive: true });
    for (const mig of m.migrations) {
      const sql = readFileSync(resolve(m.root, mig.file), "utf8");
      put(`pb_migrations/${mig.name}.void.js`, generateMigration(mig.name, sql));
    }
  }
  if (existsSync(migrationsOut) && !readdirSync(migrationsOut).length) rmSync(migrationsOut, { recursive: true, force: true });

  return { written, removed };
}
