// Generated by packages/voidbase/scripts/schema-sql.ts from db/migrations/*.sql; do not edit. That script
// is the repository's and is not shipped; test/unit/durable-d1.test.ts checks this file is current.
// The system tables the database Durable Object (src/server/durable-db.ts) creates on its first request: the same
// statements Void applies to a D1 database at deploy time, in the same order, one entry per migration file.
export interface SystemMigration { name: string; statements: string[] }
export const SYSTEM_MIGRATIONS: SystemMigration[] = [
  { name: "20260905175935_large_swarm", statements: [
    "CREATE TABLE `_authOrigins` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`collectionRef` text DEFAULT '' NOT NULL,\n\t`recordRef` text DEFAULT '' NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`updated` text DEFAULT '' NOT NULL,\n\t`fingerprint` text DEFAULT '' NOT NULL\n);",
    "CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (`collectionRef`,`recordRef`,`fingerprint`);",
    "CREATE TABLE `_collections` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`system` integer DEFAULT false NOT NULL,\n\t`type` text DEFAULT 'base' NOT NULL,\n\t`name` text NOT NULL,\n\t`fields` text DEFAULT '[]' NOT NULL,\n\t`indexes` text DEFAULT '[]' NOT NULL,\n\t`listRule` text,\n\t`viewRule` text,\n\t`createRule` text,\n\t`updateRule` text,\n\t`deleteRule` text,\n\t`options` text DEFAULT '{}' NOT NULL,\n\t`created` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL,\n\t`updated` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL\n);",
    "CREATE UNIQUE INDEX `_collections_name_unique` ON `_collections` (`name`);",
    "CREATE INDEX `idx__collections_type` ON `_collections` (`type`);",
    "CREATE TABLE `_externalAuths` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`collectionRef` text DEFAULT '' NOT NULL,\n\t`recordRef` text DEFAULT '' NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`updated` text DEFAULT '' NOT NULL,\n\t`provider` text DEFAULT '' NOT NULL,\n\t`providerId` text DEFAULT '' NOT NULL\n);",
    "CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (`collectionRef`,`recordRef`,`provider`);",
    "CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (`collectionRef`,`provider`,`providerId`);",
    "CREATE TABLE `_mfas` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`collectionRef` text DEFAULT '' NOT NULL,\n\t`recordRef` text DEFAULT '' NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`updated` text DEFAULT '' NOT NULL,\n\t`method` text DEFAULT '' NOT NULL\n);",
    "CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (`collectionRef`,`recordRef`);",
    "CREATE TABLE `_pbMigrations` (\n\t`file` text PRIMARY KEY NOT NULL,\n\t`applied` integer NOT NULL\n);",
    "CREATE TABLE `_otps` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`collectionRef` text DEFAULT '' NOT NULL,\n\t`recordRef` text DEFAULT '' NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`updated` text DEFAULT '' NOT NULL,\n\t`password` text DEFAULT '' NOT NULL,\n\t`sentTo` text DEFAULT '' NOT NULL\n);",
    "CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (`collectionRef`,`recordRef`);",
    "CREATE TABLE `_params` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`value` text,\n\t`created` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL,\n\t`updated` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL\n);",
    "CREATE TABLE `_superusers` (\n\t`id` text PRIMARY KEY DEFAULT ('r'||lower(hex(randomblob(7)))) NOT NULL,\n\t`password` text DEFAULT '' NOT NULL,\n\t`tokenKey` text DEFAULT '' NOT NULL,\n\t`email` text DEFAULT '' NOT NULL,\n\t`emailVisibility` integer DEFAULT false NOT NULL,\n\t`verified` integer DEFAULT false NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`updated` text DEFAULT '' NOT NULL\n);",
    "CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`);",
    "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE \"_superusers\".\"email\" != '';",
  ] },
  { name: "20260905185720_wild_sunspot", statements: [
    "CREATE TABLE `_changes` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`collection` text NOT NULL,\n\t`recordId` text NOT NULL,\n\t`action` text NOT NULL,\n\t`created` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL\n);",
    "CREATE INDEX `idx__changes_collection` ON `_changes` (`collection`,`id`);",
    "CREATE TABLE `_realtime_clients` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`subscriptions` text DEFAULT '[]' NOT NULL,\n\t`token` text DEFAULT '' NOT NULL,\n\t`created` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL,\n\t`updated` text DEFAULT (strftime('%Y-%m-%d %H:%M:%fZ')) NOT NULL\n);",
  ] },
  { name: "20260905190723_solid_toro", statements: [
    "ALTER TABLE `_changes` ADD `data` text;",
  ] },
  { name: "20260905213340_remarkable_union_jack", statements: [
    "CREATE TABLE `_logs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created` text DEFAULT '' NOT NULL,\n\t`data` text DEFAULT '{}' NOT NULL,\n\t`message` text DEFAULT '' NOT NULL,\n\t`level` integer DEFAULT 0 NOT NULL\n);",
    "CREATE INDEX `idx_logs_created` ON `_logs` (`created`);",
    "CREATE INDEX `idx_logs_level` ON `_logs` (`level`);",
    "CREATE INDEX `idx_logs_message` ON `_logs` (`message`);",
  ] },
];
