// Writes src/server/schema-sql.ts from db/migrations/*.sql: the system tables as the database Durable Object
// (src/server/durable-db.ts) creates them, the same statements Void applies to a D1 at deploy time.
//   bun packages/voidbase/scripts/schema-sql.ts   (test/unit/durable-d1.test.ts fails when the module is out of
//                                                  date). Repository tooling: the package does not ship this file.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
export const SCHEMA_SQL_FILE = resolve(ROOT, "src/server/schema-sql.ts");

/** the migration files split into statements, in file order (drizzle's `--> statement-breakpoint` separates them) */
export function systemMigrations(dir = resolve(ROOT, "db/migrations")): { name: string; statements: string[] }[] {
  return readdirSync(dir).filter((f) => f.endsWith(".sql")).sort().map((f) => ({
    name: f.replace(/\.sql$/, ""),
    statements: readFileSync(resolve(dir, f), "utf8").split("--> statement-breakpoint").map((s) => s.trim()).filter(Boolean),
  }));
}

export function schemaSqlSource(dir?: string): string {
  const body = systemMigrations(dir).map((m) => `  { name: ${JSON.stringify(m.name)}, statements: [\n${m.statements.map((s) => `    ${JSON.stringify(s)},`).join("\n")}\n  ] },`).join("\n");
  return `// Generated by packages/voidbase/scripts/schema-sql.ts from db/migrations/*.sql; do not edit. That script
// is the repository's and is not shipped; test/unit/durable-d1.test.ts checks this file is current.
// The system tables the database Durable Object (src/server/durable-db.ts) creates on its first request: the same
// statements Void applies to a D1 database at deploy time, in the same order, one entry per migration file.
export interface SystemMigration { name: string; statements: string[] }
export const SYSTEM_MIGRATIONS: SystemMigration[] = [
${body}
];
`;
}

if (import.meta.main) { writeFileSync(SCHEMA_SQL_FILE, schemaSqlSource()); console.log(`wrote ${SCHEMA_SQL_FILE}`); }
