// The share card's font, subset and written as `src/server/plugins/og-font.ts`.
//
// A Worker has no system fonts, so the card's text would come out blank once it is rasterised to PNG. The card
// therefore carries its own faces. This script fetches Inter (SIL Open Font License 1.1) from google/fonts at one
// pinned commit, cuts it down to the characters a card can show, pins the variable axes to two static weights
// (400 for the app name and the description, 700 for the title) and writes both faces into a TypeScript module as
// base64. The module is committed, so a build never reaches the network and two checkouts produce the same bytes.
//
//   bun scripts/og-font.ts          rewrite src/server/plugins/og-font.ts
//   bun scripts/og-font.ts --check  fail when the committed file is not what this script produces
//
// The character set is ASCII plus Latin-1's printable half plus the punctuation the card's own wrapping can emit
// (the ellipsis it closes a cut line with, curly quotes, dashes). A title with a character outside it renders with
// resvg's notdef glyph rather than a wrong glyph, which is the failure you want: visible, not silent.
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import subsetFont from "subset-font";

const COMMIT = "e1d6480102fed30739fead0faee463101f892c8f";
const URL = `https://raw.githubusercontent.com/google/fonts/${COMMIT}/ofl/inter/Inter%5Bopsz%2Cwght%5D.ttf`;
const FAMILY = "Inter";
const WEIGHTS = [400, 700] as const;
const OPSZ = 14; // the optical size axis pinned where Inter's own "text" instance sits
const OUT = resolve(import.meta.dir, "../src/server/plugins/og-font.ts");

const range = (from: number, to: number): string => { let s = ""; for (let cp = from; cp <= to; cp++) s += String.fromCodePoint(cp); return s; };
/** ASCII, Latin-1's printable half, and the punctuation the card's wrapping and the excerpt can emit */
const CHARS = `${range(0x20, 0x7e)}${range(0xa0, 0xff)}‘’“”–—…·€™`;

async function build(): Promise<string> {
  const res = await fetch(URL);
  if (!res.ok) throw new Error(`Inter could not be fetched from google/fonts@${COMMIT.slice(0, 7)}: ${res.status}`);
  const src = Buffer.from(await res.arrayBuffer());
  const faces: string[] = [];
  for (const wght of WEIGHTS) {
    const out = await subsetFont(src, CHARS, { targetFormat: "truetype", variationAxes: { wght, opsz: OPSZ } });
    console.log(`  ${FAMILY} ${wght}: ${out.length} bytes (${Math.round((out.length / 1024) * 10) / 10} KB)`);
    faces.push(out.toString("base64"));
  }
  const lines = [
    `// GENERATED by scripts/og-font.ts. Do not edit: run \`bun scripts/og-font.ts\` instead.`,
    `//`,
    `// Inter, subset to ASCII + Latin-1 + the card's own punctuation and pinned to two static weights, from`,
    `// google/fonts@${COMMIT} (ofl/inter/Inter[opsz,wght].ttf, opsz ${OPSZ}).`,
    `// SIL Open Font License 1.1, Copyright 2020 The Inter Project Authors. See NOTICE.`,
    `//`,
    `// A Worker has no system fonts, so the rasteriser is handed these two faces and the card's SVG names the`,
    `// family first in its font stack. Only the rasteriser imports this module, and only on the first .png request,`,
    `// so the bytes stay out of every other request's cold start.`,
    ``,
    `/** the family name the card's SVG asks for, ahead of the generic stack */`,
    `export const OG_FONT_FAMILY = ${JSON.stringify(FAMILY)};`,
    `/** the weights the two faces carry: the card's title is ${WEIGHTS[1]}, everything else ${WEIGHTS[0]} */`,
    `export const OG_FONT_WEIGHTS = [${WEIGHTS.join(", ")}] as const;`,
    ``,
    ...WEIGHTS.flatMap((w, i) => [`const FACE_${w} = "${faces[i]}";`, ``]),
    `const bytes = (b64: string): Uint8Array => { const s = atob(b64); const out = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i); return out; };`,
    ``,
    `/** the faces as raw TrueType buffers, in the order resvg should see them */`,
    `export const ogFontBuffers = (): Uint8Array[] => [${WEIGHTS.map((w) => `bytes(FACE_${w})`).join(", ")}];`,
    ``,
  ];
  return lines.join("\n");
}

const text = await build();
if (process.argv.includes("--check")) {
  const same = existsSync(OUT) && readFileSync(OUT, "utf8") === text;
  console.log(same ? `og-font.ts is what scripts/og-font.ts produces` : `og-font.ts is stale: run \`bun scripts/og-font.ts\``);
  process.exit(same ? 0 : 1);
}
writeFileSync(OUT, text);
console.log(`wrote ${OUT} (${Math.round((text.length / 1024) * 10) / 10} KB of source)`);
